# Generated by Django 4.1.7 on 2023-02-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cve", old_name="editado", new_name="ultimaModificacion",
        ),
    ]
