version: '3.7'

services:

  backend:
    container_name: ${PROJECT_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - appdata:/code

volumes:

    appdata:
        driver: local




        